### PR TITLE
Add download of checksum file, verification of complete product file download

### PR DESCRIPTION
**Pull request by nitzanhanyvision**

### CODE REVIEW

**Comment by nitzanhanyvision** [comment]
@sashas-anyvision

**Comment by sashas-anyvision** [comment]
@nitzanhanyvision  are you merging this ?

**Comment by sashas-anyvision** [comment]
@nitzanhanyvision  are we merging this ?

**Comment by nitzanhanyvision** [comment]
> @nitzanhanyvision are we merging this ?

Merged

**Pull request merged**
