### PR TITLE
oneliner: is not working on RHEL

### PR DESCRIPTION
**Pull request by igaldahan**
description: seems that rhel packages are not downloaded and thus failed on control flow ,lines 230-250

Revert "Optional nvidia driver in container (#19)"

This reverts commit 6e6be9f9eccfeb05c5c766a54e28c4349fbc15ac.

### CODE REVIEW

**Comment by igaldahan** [comment]
the option in the install.sh are : --install-method airgap --skip-product

**Comment by igaldahan** [comment]
@sashas-anyvision  @digger18 please look in the previous comment

and why not fixing? 
-- priorities 
-- timeline

**Comment by digger18** [comment]
I will look into it and fix accordingly.

**Comment by igaldahan** [comment]
the error output: 

Installing mode aio with method airgap", "Error: required file rhel-packages-20190923.tar NVIDIA-Linux-x86_64-410.104.run is missing

**Comment by igaldahan** [comment]
> I will look into it and fix accordingly.
@sashas-anyvision @digger18 
please open new PR and we will check it later on

**Pull request merged**
